name:                hackernews
version:             0.1.3.0

dependencies:
- base >= 4.7 && < 5
- aeson
- lens-aeson
- lens
- http-conduit
- streamly
- text

library:
  source-dirs: src

executables:
  hackernews-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hackernews

tests:
  hackernews-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hackernews
    - QuickCheck
